# Generated by Django 4.1.3 on 2022-11-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.ManyToManyField(null=True, to='students.student'),
        ),
    ]
