# Generated by Django 4.1.3 on 2022-11-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_group_group_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ManyToManyField(to='students.student'),
        ),
    ]
