# Generated by Django 4.1.3 on 2022-12-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_group_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
